#TODO RUNNING IN PRODUCTION SHOULD USE AN EXTERNAL DB INSTEAD OF LAUNCHING ONE INSIDE A CONTAINER (EG:RDS). When ready for
#TODO prod, set up a new instance of DB and make sure app uses that in prod and does not create local version
# Do not start versioning the DB while it does not have a somewhat settled structure. Then go through this blog: https://guillaume-martin.github.io/db-versioning-liquibase-part-1.html
services:
#  web:
#    build: .
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env # make .env file reachable inside the Dockerfile, which then can pass them to spring boot args
  db:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '6432:5432' # Have to use different port outside otherwise cannot connect with dbeaver for some reason
    volumes:
#      - ./postgres/data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

